services:
  - docker

env:
  global:
    - RELEASE_VERSION=2.3
    - NOMINATIM_PBF_URL="http://download.geofabrik.de/asia/maldives-latest.osm.pbf"

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

install:
  - docker build -t nominatim-k8s ./$RELEASE_VERSION
  - docker run -d -p 8080:8080 -e NOMINATIM_PBF_URL=$NOMINATIM_PBF_URL --name nominatim nominatim-k8s

before_script:
  - npm install newman --global

script:
  - docker ps | grep -q nominatim-k8s
  - ./tests/wait-for-http.sh http://localhost:8080/search
  - newman run tests/nominatim.postman_collection.json
  